//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.visitor;
import java.util.Enumeration;

import org.pingel.gestalt.parser.syntaxtree.Application;
import org.pingel.gestalt.parser.syntaxtree.Expression;
import org.pingel.gestalt.parser.syntaxtree.Form;
import org.pingel.gestalt.parser.syntaxtree.GSystem;
import org.pingel.gestalt.parser.syntaxtree.Goal;
import org.pingel.gestalt.parser.syntaxtree.Identifier;
import org.pingel.gestalt.parser.syntaxtree.Include;
import org.pingel.gestalt.parser.syntaxtree.Node;
import org.pingel.gestalt.parser.syntaxtree.NodeList;
import org.pingel.gestalt.parser.syntaxtree.NodeListOptional;
import org.pingel.gestalt.parser.syntaxtree.NodeOptional;
import org.pingel.gestalt.parser.syntaxtree.NodeSequence;
import org.pingel.gestalt.parser.syntaxtree.NodeToken;
import org.pingel.gestalt.parser.syntaxtree.Path;
import org.pingel.gestalt.parser.syntaxtree.Statement;
import org.pingel.gestalt.parser.syntaxtree.Substitution;
import org.pingel.gestalt.parser.syntaxtree.Transform;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration e = n.elements(); e.hasMoreElements(); )
         ((Node)e.nextElement()).accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration e = n.elements(); e.hasMoreElements(); )
            ((Node)e.nextElement()).accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration e = n.elements(); e.hasMoreElements(); )
         ((Node)e.nextElement()).accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Statement() )*
    * f1 -> <EOF>
    */
   public void visit(Goal n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Transform()
    *       | GSystem()
    *       | Form()
    *       | Include()
    */
   public void visit(Statement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "include"
    * f1 -> Identifier()
    */
   public void visit(Include n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "transform"
    * f1 -> Identifier()
    * f2 -> Identifier()
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( Substitution() )*
    * f6 -> "}"
    * f7 -> ( "$" Identifier() )?
    */
   public void visit(Transform n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> Identifier()
    * f1 -> "/"
    * f2 -> Identifier()
    */
   public void visit(Substitution n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "system"
    * f1 -> Identifier()
    * f2 -> Identifier()
    * f3 -> "{"
    * f4 -> ( Application() )*
    * f5 -> "}"
    * f6 -> "<"
    * f7 -> ( Identifier() )*
    * f8 -> ">"
    */
   public void visit(GSystem n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> "apply"
    * f1 -> Identifier()
    * f2 -> Identifier()
    * f3 -> ( Path() )?
    * f4 -> Identifier()
    */
   public void visit(Application n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "form"
    * f1 -> Identifier()
    * f2 -> "["
    * f3 -> ( Identifier() )*
    * f4 -> "]"
    * f5 -> Expression()
    */
   public void visit(Form n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> Identifier()
    *       | "(" Expression() Expression() ")"
    */
   public void visit(Expression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <PATH>
    */
   public void visit(Path n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Identifier n) {
      n.f0.accept(this);
   }

}
