/* Generated By:JavaCC: Do not edit this line. GestaltParserConstants.java */
package org.pingel.gestalt.parser;

public interface GestaltParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int LANGBRACKET = 9;
  int RANGBRACKET = 10;
  int LSQPAREN = 11;
  int RSQPAREN = 12;
  int LBRACE = 13;
  int RBRACE = 14;
  int DOT = 15;
  int SLASH = 16;
  int DOLLAR = 17;
  int SYSTEM = 18;
  int TRANSFORM = 19;
  int FORM = 20;
  int APPLY = 21;
  int INCLUDE = 22;
  int PATH = 23;
  int PATHELEM = 24;
  int IDENTIFIER = 25;
  int LETTER = 26;
  int DIGIT = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"/\"",
    "\"$\"",
    "\"system\"",
    "\"transform\"",
    "\"form\"",
    "\"apply\"",
    "\"include\"",
    "<PATH>",
    "<PATHELEM>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
  };

}
