//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> "form"
 * f1 -> Identifier()
 * f2 -> "["
 * f3 -> ( Identifier() )*
 * f4 -> "]"
 * f5 -> Expression()
 */
public class Form implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeToken f2;
   public NodeListOptional f3;
   public NodeToken f4;
   public Expression f5;

   public Form(NodeToken n0, Identifier n1, NodeToken n2, NodeListOptional n3, NodeToken n4, Expression n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public Form(Identifier n0, NodeListOptional n1, Expression n2) {
      f0 = new NodeToken("form");
      f1 = n0;
      f2 = new NodeToken("[");
      f3 = n1;
      f4 = new NodeToken("]");
      f5 = n2;
   }

   public void accept(org.pingel.gestalt.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.pingel.gestalt.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

