//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> "apply"
 * f1 -> Identifier()
 * f2 -> Identifier()
 * f3 -> ( Path() )?
 * f4 -> Identifier()
 */
public class Application implements Node {
   public NodeToken f0;
   public Identifier f1;
   public Identifier f2;
   public NodeOptional f3;
   public Identifier f4;

   public Application(NodeToken n0, Identifier n1, Identifier n2, NodeOptional n3, Identifier n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public Application(Identifier n0, Identifier n1, NodeOptional n2, Identifier n3) {
      f0 = new NodeToken("apply");
      f1 = n0;
      f2 = n1;
      f3 = n2;
      f4 = n3;
   }

   public void accept(org.pingel.gestalt.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.pingel.gestalt.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

