//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( Statement() )*
 * f1 -> <EOF>
 */
public class Goal implements Node {
   public NodeListOptional f0;
   public NodeToken f1;

   public Goal(NodeListOptional n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public Goal(NodeListOptional n0) {
      f0 = n0;
      f1 = new NodeToken("");
   }

   public void accept(org.pingel.gestalt.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.pingel.gestalt.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

