//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> "system"
 * f1 -> Identifier()
 * f2 -> Identifier()
 * f3 -> "{"
 * f4 -> ( Application() )*
 * f5 -> "}"
 * f6 -> "<"
 * f7 -> ( Identifier() )*
 * f8 -> ">"
 */
public class GSystem implements Node {
   public NodeToken f0;
   public Identifier f1;
   public Identifier f2;
   public NodeToken f3;
   public NodeListOptional f4;
   public NodeToken f5;
   public NodeToken f6;
   public NodeListOptional f7;
   public NodeToken f8;

   public GSystem(NodeToken n0, Identifier n1, Identifier n2, NodeToken n3, NodeListOptional n4, NodeToken n5, NodeToken n6, NodeListOptional n7, NodeToken n8) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
   }

   public GSystem(Identifier n0, Identifier n1, NodeListOptional n2, NodeListOptional n3) {
      f0 = new NodeToken("system");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("{");
      f4 = n2;
      f5 = new NodeToken("}");
      f6 = new NodeToken("<");
      f7 = n3;
      f8 = new NodeToken(">");
   }

   public void accept(org.pingel.gestalt.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.pingel.gestalt.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

