//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> "include"
 * f1 -> Identifier()
 */
public class Include implements Node {
   public NodeToken f0;
   public Identifier f1;

   public Include(NodeToken n0, Identifier n1) {
      f0 = n0;
      f1 = n1;
   }

   public Include(Identifier n0) {
      f0 = new NodeToken("include");
      f1 = n0;
   }

   public void accept(org.pingel.gestalt.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.pingel.gestalt.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

