//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> Identifier()
 * f1 -> "/"
 * f2 -> Identifier()
 */
public class Substitution implements Node {
   public Identifier f0;
   public NodeToken f1;
   public Identifier f2;

   public Substitution(Identifier n0, NodeToken n1, Identifier n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Substitution(Identifier n0, Identifier n1) {
      f0 = n0;
      f1 = new NodeToken("/");
      f2 = n1;
   }

   public void accept(org.pingel.gestalt.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.pingel.gestalt.parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

