addSbtPlugin("com.eed3si9n"         % "sbt-unidoc"            % "0.4.1")
addSbtPlugin("com.github.gseitz"    % "sbt-release"           % "1.0.6")
addSbtPlugin("com.typesafe"         % "sbt-mima-plugin"       % "0.7.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-site"              % "1.3.2")
addSbtPlugin("org.scalameta"        % "sbt-mdoc"              % "2.2.5")
addSbtPlugin("pl.project13.scala"   % "sbt-jmh"               % "0.2.27")
addSbtPlugin("org.scalastyle"      %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"         % "1.5.1")
addSbtPlugin("com.typesafe.sbt"     % "sbt-git"               % "0.9.3")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"           % "0.6.20")
addSbtPlugin("com.github.tkawachi"  % "sbt-doctest"           % "0.7.0")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"          % "3.9.3")
addSbtPlugin("com.jsuereth"         % "sbt-pgp"               % "2.0.1")
addSbtPlugin("org.lyranthe.sbt"     % "partial-unification"   % "1.1.2")
// addSbtPlugin("net.virtual-void"     % "sbt-dependency-graph"  % "0.8.2")
