//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.visitor;
import org.pingel.gestalt.parser.syntaxtree.Application;
import org.pingel.gestalt.parser.syntaxtree.Expression;
import org.pingel.gestalt.parser.syntaxtree.Form;
import org.pingel.gestalt.parser.syntaxtree.GSystem;
import org.pingel.gestalt.parser.syntaxtree.Goal;
import org.pingel.gestalt.parser.syntaxtree.Identifier;
import org.pingel.gestalt.parser.syntaxtree.Include;
import org.pingel.gestalt.parser.syntaxtree.NodeList;
import org.pingel.gestalt.parser.syntaxtree.NodeListOptional;
import org.pingel.gestalt.parser.syntaxtree.NodeOptional;
import org.pingel.gestalt.parser.syntaxtree.NodeSequence;
import org.pingel.gestalt.parser.syntaxtree.NodeToken;
import org.pingel.gestalt.parser.syntaxtree.Path;
import org.pingel.gestalt.parser.syntaxtree.Statement;
import org.pingel.gestalt.parser.syntaxtree.Substitution;
import org.pingel.gestalt.parser.syntaxtree.Transform;

/**
 * All Object visitors must implement this interface.
 */
public interface ObjectVisitor {
   //
   // Object Auto class visitors
   //
   public Object visit(NodeList n, Object argu);
   public Object visit(NodeListOptional n, Object argu);
   public Object visit(NodeOptional n, Object argu);
   public Object visit(NodeSequence n, Object argu);
   public Object visit(NodeToken n, Object argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Statement() )*
    * f1 -> <EOF>
    */
   public Object visit(Goal n, Object argu);

   /**
    * f0 -> Transform()
    *       | GSystem()
    *       | Form()
    *       | Include()
    */
   public Object visit(Statement n, Object argu);

   /**
    * f0 -> "include"
    * f1 -> Identifier()
    */
   public Object visit(Include n, Object argu);

   /**
    * f0 -> "transform"
    * f1 -> Identifier()
    * f2 -> Identifier()
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( Substitution() )*
    * f6 -> "}"
    * f7 -> ( "$" Identifier() )?
    */
   public Object visit(Transform n, Object argu);

   /**
    * f0 -> Identifier()
    * f1 -> "/"
    * f2 -> Identifier()
    */
   public Object visit(Substitution n, Object argu);

   /**
    * f0 -> "system"
    * f1 -> Identifier()
    * f2 -> Identifier()
    * f3 -> "{"
    * f4 -> ( Application() )*
    * f5 -> "}"
    * f6 -> "<"
    * f7 -> ( Identifier() )*
    * f8 -> ">"
    */
   public Object visit(GSystem n, Object argu);

   /**
    * f0 -> "apply"
    * f1 -> Identifier()
    * f2 -> Identifier()
    * f3 -> ( Path() )?
    * f4 -> Identifier()
    */
   public Object visit(Application n, Object argu);

   /**
    * f0 -> "form"
    * f1 -> Identifier()
    * f2 -> "["
    * f3 -> ( Identifier() )*
    * f4 -> "]"
    * f5 -> Expression()
    */
   public Object visit(Form n, Object argu);

   /**
    * f0 -> Identifier()
    *       | "(" Expression() Expression() ")"
    */
   public Object visit(Expression n, Object argu);

   /**
    * f0 -> <PATH>
    */
   public Object visit(Path n, Object argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public Object visit(Identifier n, Object argu);

}
