//
// Generated by JTB 1.2.2
//

package org.pingel.gestalt.parser.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(org.pingel.gestalt.parser.visitor.Visitor v);
   public Object accept(org.pingel.gestalt.parser.visitor.ObjectVisitor v, Object argu);

}

